stages:
  - deploy

variables:
  EC2_HOST: "api.bablyapp.com"
  EC2_USER: "ec2-user
  SSH_KEY_PATH: ".ci/keys/deploy_key"

before_script:
  - eval $(ssh-agent -s)
  - chmod 600 $SSH_KEY_PATH
  - echo "Adding deploy key to agent..."
  - ssh-add $SSH_KEY_PATH
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

deploy:
  stage: deploy
  script:
    - echo "Deploying to $EC2_HOST"
    - ssh $EC2_USER@$EC2_HOST "pm2 stop all || true"
    - rsync -avz --exclude '.git' --exclude 'node_modules' ./ $EC2_USER@$EC2_HOST:~/app/
    - ssh $EC2_USER@$EC2_HOST <<EOF
        cd ~/app &&
        npm install &&
        pm2 start ecosystem.config.js || pm2 restart ecosystem.config.js
      EOF
  only:
    - working_branch
