name: Deploy to EC2

on:
  push:
    branches:
      - main   # or 'working_branch' if that’s your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/deploy_key
          ssh-keyscan -H api.bablyapp.com >> ~/.ssh/known_hosts

      - name: Deploy to EC2 via rsync
        run: |
          echo "Deploying project to EC2..."
          rsync -avzr --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='.ci' \
            --exclude='client' \
            ./ ec2-user@api.bablyapp.com:/home/ec2-user/project/

      - name: Restart app on EC2
        run: |
          ssh ec2-user@api.bablyapp.com '
            cd /home/ec2-user/project &&
            sh scripts/ec2env.sh &&
            sh database/import.sh &&
            cd server &&
            npm install &&
            pm2 restart all || pm2 start --time npm -- start
          '
