name: Deploy to EC2

on:
  push:
    branches:
      - main   # change if your deploy branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_HOST: api.bablyapp.com
          DEPLOY_USER: ec2-user
          DEPLOY_PATH: /home/ec2-user/project
        run: |
          # Set up SSH
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" | base64 --decode > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts 2>/dev/null
          
          # Deploy via rsync
          echo "Deploying project to EC2..."
          rsync -avzr -e "ssh -i ~/.ssh/deploy_key" --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='.ci' \
            --exclude='client' \
            ./ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/
          
          # Restart app on EC2
          echo "Restarting application..."
          ssh -i ~/.ssh/deploy_key $DEPLOY_USER@$DEPLOY_HOST "
            cd $DEPLOY_PATH &&
            sh scripts/ec2env.sh &&
            sh database/import.sh &&
            cd server &&
            npm install &&
            pm2 restart all || pm2 start --time npm -- start
          "